const eventSoccerStats = {
    "results": [
        {
            "type": "EVENT",
            "C1_ID, MINI_DIARY_C1": "1",
            "C2_ID, MINI_DIARY_C2": "52102803",
            "BET_TYPE_PULL, COMPETITION_CODE": "COSTARICA-PRI",
            "COMPETITION_KEY": "COSTARICA-PRI",
            "CLASSIFICATION": "1",
            "COMPETITION_NAME": "Costa Rica Primera Division",
            "DISPLAY_CLOCK": "1",
            "EXTRA_DATA_2, TEAM_ODDS_A": "",
            "EXTRA_STATS_AVAILABLE": "0",
            "EXTRA_DATA_1, TEAM_ODDS_H": "",
            "FIXTURE_PARENT_ID": "92667833",
            "ID": "92667833C1A_1",
            "TOPIC_ID": "15521028032M1_1",
            "INFO_POD_LINK_1_DISPLAY_TEXT": "1",
            "LT": "1-208648",
            "MATCHLIVE_PERIOD": "1",
            "MATCH_LENGTH": "90",
            "NAME": "Alajuelense v Santos de Guápiles",
            "PENALTY_GOALS, MATCHLIVE_ADDITIONAL_INFO, PAGE_TYPE": "",
            "MATCHLIVE_STATS_1": "On Target",
            "MATCHLIVE_STATS_2": "Off Target",
            "MATCHLIVE_STATS_3": "Attacks",
            "MATCHLIVE_STATS_4": "Dangerous Attacks",
            "MATCHLIVE_STATS_5": "03:00#-1",
            "MATCHLIVE_STATS_6": "##-1",
            "MATCHLIVE_STATS_7": "Possession %",
            "MATCHLIVE_STATS_8": "20200902030000",
            "SPOTLIGHT_FORM": "0",
            "SHORT_SCORE, SUSPENDED_SELECTION": "0-1",
            "MATCHLIVE_AVAILABLE": "1",
            "C1_TABLE, MINI_DIARY_T1, TEXT_1": "5",
            "C2_TABLE, MINI_DIARY_T2, TEXT_2": "2",
            "TIME_ADDED": "",
            "COUNTDOWN, TAX_DETAILS": "0",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": "45",
            "TMR_SECS, TOTE_NAMES": "0",
            "TMR_TICKING": "0",
            "TMR_UPDATED": "20200902034453",
            "MATCHLIVE_ANIMATION": "1015",
            "EXTRA_TIME_LENGTH": "30",
            "MATCHLIVE_COORDINATES": ""
        },
        {
            "type": "TEAM_GROUP",
            "ADDITIONAL_DATA, TEAM_TOUCHDOWN_QUOTE": "",
            "COMPETITION_NAME": "Soccer",
            "DISPLAY_SCORE": "1",
            "EXTRA_DATA_2, TEAM_ODDS_A": "",
            "ID": "92667833",
            "TOPIC_ID": "ML92667833C1G_1",
            "ORDER": "0"
        },
        {
            "type": "TEAM",
            "DATA_1": "",
            "EXTRA_DATA_1, TEAM_ODDS_H": "",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1T1_1",
            "KIT_COLORS": "#0A0A0A,#C40010,#0A0A0A,#C40010,#C40010,#0046A8,#0A0A0A",
            "KIT_ID": "6",
            "NAME": "Alajuelense",
            "ORDER": "0",
            "PLAYING_INDICATOR, AUS_TOTE_COMBINATION": "0",
            "POD_STACK_ORDER, POINTS": "0",
            "MATCHLIVE_STATS_1": "0",
            "MATCHLIVE_STATS_2": "5",
            "MATCHLIVE_STATS_3": "66",
            "MATCHLIVE_STATS_4": "31",
            "MATCHLIVE_STATS_5": "",
            "MATCHLIVE_STATS_6": "",
            "MATCHLIVE_STATS_7": "52",
            "MATCHLIVE_STATS_8": "",
            "SCORE, SCORES_COLUMN": "0",
            "BET_TOTE_TYPE, TEAM_COLOR": "#D61414",
            "COUNTDOWN, TAX_DETAILS": "10045"
        },
        {
            "type": "TEAM",
            "DATA_1": "",
            "EXTRA_DATA_1, TEAM_ODDS_H": "",
            "ID": "2",
            "TOPIC_ID": "ML92667833C1T2_1",
            "KIT_COLORS": "#F0F0F0,#F0F0F0,#F0F0F0,#00C1BA,#C40010,#0046A8,#F0F0F0",
            "KIT_ID": "1",
            "NAME": "Santos de Guápiles",
            "ORDER": "1",
            "PLAYING_INDICATOR, AUS_TOTE_COMBINATION": "0",
            "POD_STACK_ORDER, POINTS": "0",
            "MATCHLIVE_STATS_1": "1",
            "MATCHLIVE_STATS_2": "3",
            "MATCHLIVE_STATS_3": "76",
            "MATCHLIVE_STATS_4": "45",
            "MATCHLIVE_STATS_5": "",
            "MATCHLIVE_STATS_6": "",
            "MATCHLIVE_STATS_7": "48",
            "MATCHLIVE_STATS_8": "",
            "SCORE, SCORES_COLUMN": "1",
            "BET_TOTE_TYPE, TEAM_COLOR": "#F0F0F0",
            "COUNTDOWN, TAX_DETAILS": "16484"
        },
        {
            "type": "EMBEDDED_STREAMING, EXTRA_SCORES",
            "ADDITIONAL_DATA, TEAM_TOUCHDOWN_QUOTE": "",
            "ID": "",
            "TOPIC_ID": "ML92667833C1ES_1",
            "NAME": "",
            "ORDER": "0",
            "PARTICIPANTS_EXCEEDED, PERIOD": "",
            "STYLE": ""
        },
        {
            "type": "SCORE, SCORES_COLUMN",
            "ID": "0",
            "TOPIC_ID": "ML92667833C1ES0_1",
            "NAME": "",
            "ORDER": "0",
            "STYLE": "13",
            "VISIBLE": "1"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "Alajuelense",
            "DATA_2": "",
            "ID": "0",
            "TOPIC_ID": "ML92667833C1ES0-0_1",
            "ORDER": "0",
            "STYLE": "0"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "Santos de Guápiles",
            "DATA_2": "",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1ES0-1_1",
            "ORDER": "1",
            "STYLE": "0"
        },
        {
            "type": "SCORE, SCORES_COLUMN",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1ES1_1",
            "NAME": "IGoal",
            "ORDER": "1",
            "STYLE": "14",
            "VISIBLE": "1"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "0",
            "DATA_2": "",
            "ID": "0",
            "TOPIC_ID": "ML92667833C1ES1-0_1",
            "ORDER": "0",
            "STYLE": "0"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "1",
            "DATA_2": "",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1ES1-1_1",
            "ORDER": "1",
            "STYLE": "0"
        },
        {
            "type": "SCORE, SCORES_COLUMN",
            "ID": "2",
            "TOPIC_ID": "ML92667833C1ES2_1",
            "NAME": "ICorner",
            "ORDER": "2",
            "STYLE": "14",
            "VISIBLE": "1"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "4",
            "DATA_2": "",
            "ID": "0",
            "TOPIC_ID": "ML92667833C1ES2-0_1",
            "ORDER": "0",
            "STYLE": "0"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "1",
            "DATA_2": "",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1ES2-1_1",
            "ORDER": "1",
            "STYLE": "0"
        },
        {
            "type": "SCORE, SCORES_COLUMN",
            "ID": "3",
            "TOPIC_ID": "ML92667833C1ES3_1",
            "NAME": "IYellowCard",
            "ORDER": "3",
            "STYLE": "14",
            "VISIBLE": "1"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "2",
            "DATA_2": "",
            "ID": "0",
            "TOPIC_ID": "ML92667833C1ES3-0_1",
            "ORDER": "0",
            "STYLE": "0"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "2",
            "DATA_2": "",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1ES3-1_1",
            "ORDER": "1",
            "STYLE": "0"
        },
        {
            "type": "SCORE, SCORES_COLUMN",
            "ID": "4",
            "TOPIC_ID": "ML92667833C1ES4_1",
            "NAME": "IRedCard",
            "ORDER": "4",
            "STYLE": "14",
            "VISIBLE": "1"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "0",
            "DATA_2": "",
            "ID": "0",
            "TOPIC_ID": "ML92667833C1ES4-0_1",
            "ORDER": "0",
            "STYLE": "0"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "0",
            "DATA_2": "",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1ES4-1_1",
            "ORDER": "1",
            "STYLE": "0"
        },
        {
            "type": "SCORE, SCORES_COLUMN",
            "ID": "5",
            "TOPIC_ID": "ML92667833C1ES5_1",
            "NAME": "IThrowIn",
            "ORDER": "5",
            "STYLE": "14",
            "VISIBLE": "1"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "-",
            "DATA_2": "",
            "ID": "0",
            "TOPIC_ID": "ML92667833C1ES5-0_1",
            "ORDER": "0",
            "STYLE": "0"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "-",
            "DATA_2": "",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1ES5-1_1",
            "ORDER": "1",
            "STYLE": "0"
        },
        {
            "type": "SCORE, SCORES_COLUMN",
            "ID": "6",
            "TOPIC_ID": "ML92667833C1ES6_1",
            "NAME": "IFreeKick",
            "ORDER": "6",
            "STYLE": "14",
            "VISIBLE": "1"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "-",
            "DATA_2": "",
            "ID": "0",
            "TOPIC_ID": "ML92667833C1ES6-0_1",
            "ORDER": "0",
            "STYLE": "0"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "-",
            "DATA_2": "",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1ES6-1_1",
            "ORDER": "1",
            "STYLE": "0"
        },
        {
            "type": "SCORE, SCORES_COLUMN",
            "ID": "7",
            "TOPIC_ID": "ML92667833C1ES7_1",
            "NAME": "IGoalKick",
            "ORDER": "7",
            "STYLE": "14",
            "VISIBLE": "1"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "-",
            "DATA_2": "",
            "ID": "0",
            "TOPIC_ID": "ML92667833C1ES7-0_1",
            "ORDER": "0",
            "STYLE": "0"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "-",
            "DATA_2": "",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1ES7-1_1",
            "ORDER": "1",
            "STYLE": "0"
        },
        {
            "type": "SCORE, SCORES_COLUMN",
            "ID": "8",
            "TOPIC_ID": "ML92667833C1ES8_1",
            "NAME": "IPenalty",
            "ORDER": "8",
            "STYLE": "14",
            "STAT_TIME, TMR_MINS": "",
            "VISIBLE": "1"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "0",
            "DATA_2": "",
            "ID": "0",
            "TOPIC_ID": "ML92667833C1ES8-0_1",
            "ORDER": "0",
            "STYLE": "0"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "0",
            "DATA_2": "",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1ES8-1_1",
            "ORDER": "1",
            "STYLE": "0"
        },
        {
            "type": "SCORE, SCORES_COLUMN",
            "ID": "9",
            "TOPIC_ID": "ML92667833C1ES9_1",
            "NAME": "ISubstitution",
            "ORDER": "9",
            "STYLE": "14",
            "VISIBLE": "1"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "1",
            "DATA_2": "",
            "ID": "0",
            "TOPIC_ID": "ML92667833C1ES9-0_1",
            "ORDER": "0",
            "STYLE": "0"
        },
        {
            "type": "SCORES_CELL",
            "DATA_1": "0",
            "DATA_2": "",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1ES9-1_1",
            "ORDER": "1",
            "STYLE": "0"
        },
        {
            "type": "STAT_GROUP",
            "DATA_2": "4,1",
            "DATA_3": "2,2",
            "DATA_4": "0,0",
            "ID": "1",
            "TOPIC_ID": "ML92667833C1U1_1",
            "ORDER": "0",
            "SHORT_SCORE, SUSPENDED_SELECTION": "0-1",
            "TIME_STAMP": "0"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "END_TIME, EVENT_TYPE": "10",
            "ICON": "1",
            "ID": "67788031",
            "TOPIC_ID": "ML92667833C1U67788031_1",
            "LABEL, INFO_POD_LINK_1_ID": "Score After First Half - 0-1",
            "ORDER": "0",
            "STAT_PERIOD": "0",
            "STAT_LOCATION": "0",
            "TMR_SERVER": "0",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": "45"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "END_TIME, EVENT_TYPE": "6",
            "ICON": "4",
            "ID": "67788024",
            "TOPIC_ID": "ML92667833C1U67788024_1",
            "LABEL, INFO_POD_LINK_1_ID": "45' - 4th Yellow Card -  (Santos de Guápiles)",
            "ORDER": "1",
            "STAT_PERIOD": "0",
            "STAT_LOCATION": "2",
            "TMR_SERVER": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": "45"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "END_TIME, EVENT_TYPE": "6",
            "ICON": "4",
            "ID": "67787999",
            "TOPIC_ID": "ML92667833C1U67787999_1",
            "LABEL, INFO_POD_LINK_1_ID": "43' - 3rd Yellow Card -  (Santos de Guápiles)",
            "ORDER": "2",
            "STAT_PERIOD": "0",
            "STAT_LOCATION": "2",
            "TMR_SERVER": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": "43"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "END_TIME, EVENT_TYPE": "6",
            "ICON": "4",
            "ID": "67787965",
            "TOPIC_ID": "ML92667833C1U67787965_1",
            "LABEL, INFO_POD_LINK_1_ID": "38' - 2nd Yellow Card -  (Alajuelense)",
            "ORDER": "3",
            "STAT_PERIOD": "0",
            "STAT_LOCATION": "2",
            "TMR_SERVER": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": "38"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "END_TIME, EVENT_TYPE": "2",
            "ICON": "7",
            "ID": "67787905",
            "TOPIC_ID": "ML92667833C1U67787905_1",
            "LABEL, INFO_POD_LINK_1_ID": "32' - 5th Corner - Alajuelense",
            "ORDER": "4",
            "STAT_PERIOD": "0",
            "STAT_LOCATION": "0",
            "TMR_SERVER": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": "32"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "END_TIME, EVENT_TYPE": "2",
            "ICON": "7",
            "ID": "67787856",
            "TOPIC_ID": "ML92667833C1U67787856_1",
            "LABEL, INFO_POD_LINK_1_ID": "28' - 4th Corner - Santos de Guápiles",
            "ORDER": "5",
            "STAT_PERIOD": "0",
            "STAT_LOCATION": "0",
            "TMR_SERVER": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": "28"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "END_TIME, EVENT_TYPE": "",
            "ICON": "7",
            "ID": "67787849",
            "TOPIC_ID": "ML92667833C1U67787849_1",
            "LABEL, INFO_POD_LINK_1_ID": "27' - Race to 3 Corners - Alajuelense",
            "ORDER": "6",
            "STAT_PERIOD": "",
            "STAT_LOCATION": "0",
            "TMR_SERVER": "",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": ""
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "END_TIME, EVENT_TYPE": "2",
            "ICON": "7",
            "ID": "67787848",
            "TOPIC_ID": "ML92667833C1U67787848_1",
            "LABEL, INFO_POD_LINK_1_ID": "27' - 3rd Corner - Alajuelense",
            "ORDER": "7",
            "STAT_PERIOD": "0",
            "STAT_LOCATION": "0",
            "TMR_SERVER": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": "27"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "END_TIME, EVENT_TYPE": "1",
            "ICON": "2",
            "ID": "67787834",
            "TOPIC_ID": "ML92667833C1U67787834_1",
            "LABEL, INFO_POD_LINK_1_ID": "27' - 1st Goal -   (Santos de Guápiles) - ",
            "ORDER": "8",
            "STAT_PERIOD": "0",
            "STAT_LOCATION": "2",
            "TMR_SERVER": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": "27"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "END_TIME, EVENT_TYPE": "2",
            "ICON": "7",
            "ID": "67787742",
            "TOPIC_ID": "ML92667833C1U67787742_1",
            "LABEL, INFO_POD_LINK_1_ID": "19' - 2nd Corner - Alajuelense",
            "ORDER": "9",
            "STAT_PERIOD": "0",
            "STAT_LOCATION": "0",
            "TMR_SERVER": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": "19"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "END_TIME, EVENT_TYPE": "6",
            "ICON": "4",
            "ID": "67787696",
            "TOPIC_ID": "ML92667833C1U67787696_1",
            "LABEL, INFO_POD_LINK_1_ID": "15' - 1st Yellow Card -  (Alajuelense)",
            "ORDER": "10",
            "STAT_PERIOD": "0",
            "STAT_LOCATION": "2",
            "TMR_SERVER": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": "15"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "END_TIME, EVENT_TYPE": "2",
            "ICON": "7",
            "ID": "67787651",
            "TOPIC_ID": "ML92667833C1U67787651_1",
            "LABEL, INFO_POD_LINK_1_ID": "10' - 1st Corner - Alajuelense",
            "ORDER": "11",
            "STAT_PERIOD": "0",
            "STAT_LOCATION": "0",
            "TMR_SERVER": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "STAT_TIME, TMR_MINS": "10"
        },
        {
            "type": "STAT_GROUP",
            "ID": "100",
            "TOPIC_ID": "ML92667833C1U100_1",
            "ORDER": "1",
            "TIME_STAMP": "1"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1011-0",
            "TOPIC_ID": "ML92667833C1U1011-0_1",
            "INFO_POD_LINK_1_C2_ID": "ST",
            "ORDER": "0",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#25'#",
            "TEAM": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.05,0.5"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1003-0",
            "TOPIC_ID": "ML92667833C1U1003-0_1",
            "INFO_POD_LINK_1_C2_ID": "GO",
            "ORDER": "1",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#25'# ",
            "TEAM": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.05,0.5"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-0",
            "TOPIC_ID": "ML92667833C1U1010-0_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "2",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#4'#",
            "TEAM": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.54,0.33"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1234-0",
            "TOPIC_ID": "ML92667833C1U1234-0_1",
            "INFO_POD_LINK_1_C2_ID": "OF",
            "ORDER": "3",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#1'#",
            "TEAM": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.09,0.33"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-1",
            "TOPIC_ID": "ML92667833C1U1010-1_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "4",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#6'#",
            "TEAM": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.61,0.16"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-2",
            "TOPIC_ID": "ML92667833C1U1010-2_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "5",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#6'#",
            "TEAM": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.31,0.59"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-3",
            "TOPIC_ID": "ML92667833C1U1010-3_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "6",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#7'#",
            "TEAM": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.21,0.29"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-4",
            "TOPIC_ID": "ML92667833C1U1010-4_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "7",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#8'#",
            "TEAM": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.76,0.25"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-5",
            "TOPIC_ID": "ML92667833C1U1010-5_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "8",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#9'#",
            "TEAM": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.22,0.44"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-6",
            "TOPIC_ID": "ML92667833C1U1010-6_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "9",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#15'#",
            "TEAM": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.42,0.78"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-7",
            "TOPIC_ID": "ML92667833C1U1010-7_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "10",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#29'#",
            "TEAM": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.16,0.1"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-8",
            "TOPIC_ID": "ML92667833C1U1010-8_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "11",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#33'#",
            "TEAM": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.4,0.39"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-9",
            "TOPIC_ID": "ML92667833C1U1010-9_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "12",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#36'#",
            "TEAM": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.48,0.29"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-10",
            "TOPIC_ID": "ML92667833C1U1010-10_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "13",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#38'#",
            "TEAM": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.38,0.76"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-11",
            "TOPIC_ID": "ML92667833C1U1010-11_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "14",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#40'#",
            "TEAM": "2",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.48,0.54"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-12",
            "TOPIC_ID": "ML92667833C1U1010-12_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "15",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#42'#",
            "TEAM": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.58,0.73"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-13",
            "TOPIC_ID": "ML92667833C1U1010-13_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "16",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#43'#",
            "TEAM": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.77,0.43"
        },
        {
            "type": "INFO_POD_DETAIL_1, STAT, POD_BODY_TEXT_1, STAKE",
            "ID": "1010-14",
            "TOPIC_ID": "ML92667833C1U1010-14_1",
            "INFO_POD_LINK_1_C2_ID": "FK",
            "ORDER": "17",
            "PAGE_DATA, POD, INFO_POD_TYPE, PULL_DELAY": "#45'#",
            "TEAM": "1",
            "LEAGUE_TOPIC, TOPIC_LIST": "",
            "MATCHLIVE_COORDINATES": "0.31,0.18"
        },
        {}
    ]
}